controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    new_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # robot_base_velocity_controller:
    #   type: "diff_drive_controller/DiffDriveController"

new_arm_controller:
  ros__parameters:
    # interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - ar3_joint_1
      - ar3_joint_2
      - ar3_joint_3
      - ar3_joint_4
      - ar3_joint_5
      - ar3_joint_6


